#!/bin/sh
set -eu

tdir=$(dirname "$0")
root=$tdir/..

cd -- "$root"

# List of schemes to use.  For each scheme you need to provide a
# interpret_SCHEME unary function invoking the interpret for a file passed in as
# the argument.
#
# The script will execute interpret_SCHEME function for every file matching the
# tests/SCHEME-*.scm glob pattern.
schemes='
	chibi
	chicken
	gauche
	guile
'

interpret_chibi() {
	chibi-scheme -I. -Itests "$@"
}

interpret_chicken() {
	csi -s "$@"
}

interpret_gauche() {
	gosh -I. -Itests "$@"
}

interpret_guile() {
	# While compilation gives better error messages, it is way too slow.
	guile --no-auto-compile -L . -s "$@"
}

for scheme in $schemes; do
	for t in tests/$scheme-*.scm; do
		printf '* %s:\n' "$t"
		interpret_$scheme "$t"
	done
done
